plugins {
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id 'checkstyle'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

group = 'me.motemere'
version = version = project.version

repositories {
    mavenCentral()
    maven {
        name = 'GitHubPackages'
        url = uri("https://maven.pkg.github.com/motemere/testproject-dto")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GPR_USER")
            password = project.findProperty("gpr.key") ?: System.getenv("GPR_TOKEN")
        }
    }
}

configurations {
    mockitoAgent
}

dependencies {
    implementation 'me.motemere:testproject-dto:1.0.1'

    implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation "org.springframework.integration:spring-integration-websocket:7.0.4"

    implementation 'com.fasterxml.jackson.core:jackson-databind'

    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.boot:spring-boot-kafka'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    mockitoAgent('org.mockito:mockito-core') { transitive = false }
}

test {
    useJUnitPlatform()
    jvmArgs "-javaagent:${configurations.mockitoAgent.asPath}"
    jvmArgs "-Xshare:off"
}
