server.port=8090
spring.main.banner-mode=off

logging.level.org.springframework=ERROR
logging.level.me.motemere.middleproxy=DEBUG

#logging.file.name=logs/middleproxy.log
#logging.logback.rollingpolicy.max-history=7
#logging.logback.rollingpolicy.max-file-size=10MB
#logging.logback.rollingpolicy.file-name-pattern=logs/archived/middleproxy.%d{yyyy-MM-dd}.%i.log

spring.application.name=middleproxy

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.enabled=false

websocket.url.path=/messages

kafka.bootstrapAddress=localhost:9092
message.topic.name=testproject
